name: readme-scribe

on:
  schedule:
    - cron: '0 0 */1 * *'
  push:
    branches:
      - 'master'

jobs:
  readme-scribe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: muesli/readme-scribe@master
        with:
          template: templates/README.md.tpl
          writeTo: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@master
        with:
          commit_message: 'Update generated README'
          branch: master
          commit_user_name: readme-scribe 🤖
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
